version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./:/usr/src/app/
    ports:
    - 3333:3333
    environment:
      CHOKIDAR_USEPOLLING: "true"
